### ISSUE TITLE
feat: add clear button for conversation.

### ISSUE THREAD

**Issue by owenzhao** [kspviswa/pyOllaMx#3]
Sometime I want a brand new conversation. Currently I have to close the app and reopen. It is better to add a button to clear all conversation. 

An alternative is allow to create another window.

**Comment by kspviswa** [comment]
![Screen Recording 2024-04-13 at 9 09 52 PM](https://github.com/kspviswa/pyOllaMx/assets/7476271/c7ef3710-9a60-44ed-af80-47f56e8f8d32)
Yes it is already supported. use the clear chats button right below the send button
